apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: create-metastore-schema
  name: create-metastore-schema
spec:
  containers:
    - args:
        - /opt/hive-metastore/bin/schematool
        - --verbose
        - -initSchema
        - -dbType
        - mysql
        - -userName
        - root
        - -passWord
        - mypass
        - -url
        - jdbc:mysql://metastore-db:3306/metastore_db?createDatabaseIfNotExist=true
      image: wlcamargo/hive-metastore
      name: create-metastore-schema
  restartPolicy: OnFailure
