apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: metastore-db
  name: metastore-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
