apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: metastore
  name: metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metastore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: metastore
    spec:
      containers:
        - args:
            - /opt/hive-metastore/bin/start-metastore
            - -p
            - "9083"
          env:
            - name: AWS_ACCESS_KEY_ID
              value: chapolin
            - name: AWS_SECRET_ACCESS_KEY
              value: mudar@123
          image: wlcamargo/hive-metastore
          name: metastore
          volumeMounts:
            - mountPath: /opt/hive-metastore/conf/metastore-site.xml
              name: metastore-cm0
              subPath: metastore-site.xml
            - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              name: metastore-cm1
              subPath: core-site.xml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: metastore-site.xml
                path: metastore-site.xml
            name: metastore-cm0
          name: metastore-cm0
        - configMap:
            items:
              - key: core-site.xml
                path: core-site.xml
            name: metastore-cm1
          name: metastore-cm1
