apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: metastore-db
  name: metastore-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metastore-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: metastore-db
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypass
          image: wlcamargo/mariadb
          name: metastore-db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: metastore-db
      restartPolicy: Always
      volumes:
        - name: metastore-db
          persistentVolumeClaim:
            claimName: metastore-db
