apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - |
              /usr/local/spark/sbin/start-master.sh
              start-notebook.sh --NotebookApp.token=''
          image: wlcamargo/spark-master
          name: spark-master
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          volumeMounts:
            - mountPath: /util
              name: spark-master-cm0
            - mountPath: /home/user/work
              name: spark-master-cm2
      hostname: spark-master
      restartPolicy: Always
      volumes:
        - configMap:
            name: spark-master-cm0
          name: spark-master-cm0
        - configMap:
            name: spark-master-cm2
          name: spark-master-cm2
