apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: trino
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trino
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: trino
    spec:
      containers:
        - image: wlcamargo/trino
          name: trino
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/trino/catalog/hive.properties
              name: trino-cm0
              subPath: hive.properties
            - mountPath: /etc/trino/catalog/delta.properties
              name: trino-cm1
              subPath: delta.properties
            - mountPath: /etc/trino/catalog/iceberg.properties
              name: trino-cm2
              subPath: iceberg.properties
            - mountPath: /etc/trino/catalog/postgres.properties
              name: trino-cm3
              subPath: postgres.properties
            - mountPath: /etc/trino/catalog/sqlserver.properties
              name: trino-cm4
              subPath: sqlserver.properties
      hostname: trino
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: hive.properties
                path: hive.properties
            name: trino-cm0
          name: trino-cm0
        - configMap:
            items:
              - key: delta.properties
                path: delta.properties
            name: trino-cm1
          name: trino-cm1
        - configMap:
            items:
              - key: iceberg.properties
                path: iceberg.properties
            name: trino-cm2
          name: trino-cm2
        - configMap:
            items:
              - key: postgres.properties
                path: postgres.properties
            name: trino-cm3
          name: trino-cm3
        - configMap:
            items:
              - key: sqlserver.properties
                path: sqlserver.properties
            name: trino-cm4
          name: trino-cm4
