lakehouse:
  target: dev
  outputs:
    dev:
      type: trino
      user: trino
      host: 172.21.121.140
      port: 8080
      catalog: delta
      schema: bronze
      threads: 8
      http_scheme: http
      session_properties:
        query_max_run_time: 4h
        exchange_compression: True
